// SRFI-35 condition system procedures
//
// This module implements the runtime procedures that support the SRFI-35 condition system,
// including the procedures generated by the define-condition-type macro and the core
// condition manipulation procedures.

use crate::diagnostics::{Error as DiagnosticError, Result};
use crate::eval::value::Value;
use crate::eval::Environment;
use crate::stdlib::srfi35_conditions::{
    condition_system, ConditionValue, SimpleCondition, ConditionObject,
    initialize_condition_system,
};
use crate::utils::{string_interner::StringInterner, SymbolId};
use std::collections::HashMap;
use std::sync::Arc;

// ============= MACRO SUPPORT PROCEDURES =============

/// %register-condition-type - registers a new condition type (used by macro expansion)
/// Arguments: type-name supertype-name constructor-name predicate-name field-specs
pub fn primitive_register_condition_type(args: &[Value]) -> Result<Value> {
    if args.len() != 5 {
        return Err(Box::new(DiagnosticError::runtime_error(
            format!("%register-condition-type: expected 5 arguments, got {}", args.len()),
            None,
        )));
    }

    let type_name = match &args[0] {
        Value::Literal(crate::ast::Literal::String(s)) => s.clone(),
        _ => return Err(Box::new(DiagnosticError::runtime_error(
            "%register-condition-type: type name must be a string".to_string(),
            None,
        ))),
    };

    let supertype_name = match &args[1] {
        Value::Literal(crate::ast::Literal::String(s)) => Some(s.clone()),
        Value::Nil => None,
        _ => return Err(Box::new(DiagnosticError::runtime_error(
            "%register-condition-type: supertype name must be a string or nil".to_string(),
            None,
        ))),
    };

    let constructor_name = match &args[2] {
        Value::Literal(crate::ast::Literal::String(s)) => s.clone(),
        _ => return Err(Box::new(DiagnosticError::runtime_error(
            "%register-condition-type: constructor name must be a string".to_string(),
            None,
        ))),
    };

    let predicate_name = match &args[3] {
        Value::Literal(crate::ast::Literal::String(s)) => s.clone(),
        _ => return Err(Box::new(DiagnosticError::runtime_error(
            "%register-condition-type: predicate name must be a string".to_string(),
            None,
        ))),
    };

    // Parse field specifications: list of (field-name accessor-name) pairs
    let field_specs = parse_field_specs(&args[4])?;

    // Register the condition type
    let system = condition_system();
    let field_spec_strs: Vec<(&str, &str)> = field_specs
        .iter()
        .map(|(f, a)| (f.as_str(), a.as_str()))
        .collect();

    let type_id = system.registry.register_type(
        &type_name,
        supertype_name.as_deref(),
        &constructor_name,
        &predicate_name,
        field_spec_strs,
    )?;

    // Return the condition type object
    Ok(Value::ConditionType(type_id))
}

/// %get-condition-type - retrieves a condition type by name (used by macro expansion)
pub fn primitive_get_condition_type(args: &[Value]) -> Result<Value> {
    if args.len() != 1 {
        return Err(Box::new(DiagnosticError::runtime_error(
            format!("%get-condition-type: expected 1 argument, got {}", args.len()),
            None,
        )));
    }

    let type_name = match &args[0] {
        Value::Literal(crate::ast::Literal::String(s)) => s.clone(),
        _ => return Err(Box::new(DiagnosticError::runtime_error(
            "%get-condition-type: type name must be a string".to_string(),
            None,
        ))),
    };

    let system = condition_system();
    if let Some(type_id) = system.registry.get_type_id(&type_name) {
        Ok(Value::ConditionType(type_id))
    } else {
        Err(Box::new(DiagnosticError::runtime_error(
            format!("Unknown condition type: {}", type_name),
            None,
        )))
    }
}

/// %make-condition - creates a condition object (used by macro expansion)
/// Arguments: type-name field-bindings
pub fn primitive_make_condition(args: &[Value]) -> Result<Value> {
    if args.len() != 2 {
        return Err(Box::new(DiagnosticError::runtime_error(
            format!("%make-condition: expected 2 arguments, got {}", args.len()),
            None,
        )));
    }

    let type_name = match &args[0] {
        Value::Literal(crate::ast::Literal::String(s)) => s.clone(),
        _ => return Err(Box::new(DiagnosticError::runtime_error(
            "%make-condition: type name must be a string".to_string(),
            None,
        ))),
    };

    // Parse field bindings: list of (field-name . value) pairs
    let field_bindings = parse_field_bindings(&args[1])?;

    let system = condition_system();
    let type_id = system.registry.get_type_id(&type_name)
        .ok_or_else(|| DiagnosticError::runtime_error(
            format!("Unknown condition type: {}", type_name),
            None,
        ))?;

    // Convert field names to symbol IDs
    let mut fields = HashMap::new();
    for (field_name, value) in field_bindings {
        let field_symbol = system.registry.get_interner().intern(&field_name);
        fields.insert(field_symbol, value);
    }

    let simple_condition = SimpleCondition::new(type_id, fields);
    let condition_value = ConditionValue::new(ConditionObject::simple(simple_condition));

    Ok(Value::Condition(Arc::new(condition_value)))
}

// ============= CORE CONDITION PROCEDURES =============

/// condition - creates a compound condition from multiple conditions
pub fn primitive_condition(args: &[Value]) -> Result<Value> {
    crate::stdlib::srfi35_conditions::condition_procedure(args)
}

/// simple-conditions - extracts simple conditions from a compound condition
pub fn primitive_simple_conditions(args: &[Value]) -> Result<Value> {
    crate::stdlib::srfi35_conditions::simple_conditions_procedure(args)
}

/// condition? - tests if an object is a condition
pub fn primitive_condition_p(args: &[Value]) -> Result<Value> {
    crate::stdlib::srfi35_conditions::condition_predicate(args)
}

/// condition-has-type? - tests if a condition has a specific type
pub fn primitive_condition_has_type_p(args: &[Value]) -> Result<Value> {
    crate::stdlib::srfi35_conditions::condition_has_type_procedure(args)
}

/// extract-condition - extracts conditions of a specific type
pub fn primitive_extract_condition(args: &[Value]) -> Result<Value> {
    crate::stdlib::srfi35_conditions::extract_condition_procedure(args)
}

/// condition-ref - accesses a field value from a condition
pub fn primitive_condition_ref(args: &[Value]) -> Result<Value> {
    crate::stdlib::srfi35_conditions::condition_ref_procedure(args)
}

// ============= STANDARD CONDITION CONSTRUCTORS =============

/// make-condition - creates a root condition (no fields)
pub fn primitive_make_condition_root(args: &[Value]) -> Result<Value> {
    if !args.is_empty() {
        return Err(Box::new(DiagnosticError::runtime_error(
            format!("make-condition: expected 0 arguments, got {}", args.len()),
            None,
        )));
    }

    let system = condition_system();
    let simple_condition = SimpleCondition::new(system.standard_types.condition, HashMap::new());
    let condition_value = ConditionValue::new(ConditionObject::simple(simple_condition));

    Ok(Value::Condition(Arc::new(condition_value)))
}

/// make-message-condition - creates a message condition
pub fn primitive_make_message_condition(args: &[Value]) -> Result<Value> {
    if args.len() != 1 {
        return Err(Box::new(DiagnosticError::runtime_error(
            format!("make-message-condition: expected 1 argument, got {}", args.len()),
            None,
        )));
    }

    let message = args[0].clone();
    let system = condition_system();
    let message_field = system.registry.get_interner().intern("message");
    
    let mut fields = HashMap::new();
    fields.insert(message_field, message);

    let simple_condition = SimpleCondition::new(system.standard_types.message, fields);
    let condition_value = ConditionValue::new(ConditionObject::simple(simple_condition));

    Ok(Value::Condition(Arc::new(condition_value)))
}

/// make-serious-condition - creates a serious condition
pub fn primitive_make_serious_condition(args: &[Value]) -> Result<Value> {
    if !args.is_empty() {
        return Err(Box::new(DiagnosticError::runtime_error(
            format!("make-serious-condition: expected 0 arguments, got {}", args.len()),
            None,
        )));
    }

    let system = condition_system();
    let simple_condition = SimpleCondition::new(system.standard_types.serious, HashMap::new());
    let condition_value = ConditionValue::new(ConditionObject::simple(simple_condition));

    Ok(Value::Condition(Arc::new(condition_value)))
}

/// make-error - creates an error condition
pub fn primitive_make_error(args: &[Value]) -> Result<Value> {
    if !args.is_empty() {
        return Err(Box::new(DiagnosticError::runtime_error(
            format!("make-error: expected 0 arguments, got {}", args.len()),
            None,
        )));
    }

    let system = condition_system();
    let simple_condition = SimpleCondition::new(system.standard_types.error, HashMap::new());
    let condition_value = ConditionValue::new(ConditionObject::simple(simple_condition));

    Ok(Value::Condition(Arc::new(condition_value)))
}

/// make-violation - creates a violation condition
pub fn primitive_make_violation(args: &[Value]) -> Result<Value> {
    if !args.is_empty() {
        return Err(Box::new(DiagnosticError::runtime_error(
            format!("make-violation: expected 0 arguments, got {}", args.len()),
            None,
        )));
    }

    let system = condition_system();
    let simple_condition = SimpleCondition::new(system.standard_types.violation, HashMap::new());
    let condition_value = ConditionValue::new(ConditionObject::simple(simple_condition));

    Ok(Value::Condition(Arc::new(condition_value)))
}

/// make-assertion-violation - creates an assertion violation condition
pub fn primitive_make_assertion_violation(args: &[Value]) -> Result<Value> {
    if !args.is_empty() {
        return Err(Box::new(DiagnosticError::runtime_error(
            format!("make-assertion-violation: expected 0 arguments, got {}", args.len()),
            None,
        )));
    }

    let system = condition_system();
    let simple_condition = SimpleCondition::new(system.standard_types.assertion, HashMap::new());
    let condition_value = ConditionValue::new(ConditionObject::simple(simple_condition));

    Ok(Value::Condition(Arc::new(condition_value)))
}

/// make-non-continuable-violation - creates a non-continuable violation condition
pub fn primitive_make_non_continuable_violation(args: &[Value]) -> Result<Value> {
    if !args.is_empty() {
        return Err(Box::new(DiagnosticError::runtime_error(
            format!("make-non-continuable-violation: expected 0 arguments, got {}", args.len()),
            None,
        )));
    }

    let system = condition_system();
    let simple_condition = SimpleCondition::new(system.standard_types.non_continuable, HashMap::new());
    let condition_value = ConditionValue::new(ConditionObject::simple(simple_condition));

    Ok(Value::Condition(Arc::new(condition_value)))
}

/// make-implementation-restriction-violation - creates an implementation restriction violation condition
pub fn primitive_make_implementation_restriction_violation(args: &[Value]) -> Result<Value> {
    if !args.is_empty() {
        return Err(Box::new(DiagnosticError::runtime_error(
            format!("make-implementation-restriction-violation: expected 0 arguments, got {}", args.len()),
            None,
        )));
    }

    let system = condition_system();
    let simple_condition = SimpleCondition::new(system.standard_types.implementation_restriction, HashMap::new());
    let condition_value = ConditionValue::new(ConditionObject::simple(simple_condition));

    Ok(Value::Condition(Arc::new(condition_value)))
}

// ============= STANDARD CONDITION PREDICATES =============

/// message-condition? - tests if object is a message condition
pub fn primitive_message_condition_p(args: &[Value]) -> Result<Value> {
    if args.len() != 1 {
        return Err(Box::new(DiagnosticError::runtime_error(
            format!("message-condition?: expected 1 argument, got {}", args.len()),
            None,
        )));
    }

    match &args[0] {
        Value::Condition(condition_value) => {
            let system = condition_system();
            Ok(Value::boolean(
                condition_value.condition.has_type(system.standard_types.message, &system.registry)
            ))
        }
        _ => Ok(Value::boolean(false)),
    }
}

/// serious-condition? - tests if object is a serious condition
pub fn primitive_serious_condition_p(args: &[Value]) -> Result<Value> {
    if args.len() != 1 {
        return Err(Box::new(DiagnosticError::runtime_error(
            format!("serious-condition?: expected 1 argument, got {}", args.len()),
            None,
        )));
    }

    match &args[0] {
        Value::Condition(condition_value) => {
            let system = condition_system();
            Ok(Value::boolean(
                condition_value.condition.has_type(system.standard_types.serious, &system.registry)
            ))
        }
        _ => Ok(Value::boolean(false)),
    }
}

/// error? - tests if object is an error condition
pub fn primitive_error_p(args: &[Value]) -> Result<Value> {
    if args.len() != 1 {
        return Err(Box::new(DiagnosticError::runtime_error(
            format!("error?: expected 1 argument, got {}", args.len()),
            None,
        )));
    }

    match &args[0] {
        Value::Condition(condition_value) => {
            let system = condition_system();
            Ok(Value::boolean(
                condition_value.condition.has_type(system.standard_types.error, &system.registry)
            ))
        }
        _ => Ok(Value::boolean(false)),
    }
}

/// violation? - tests if object is a violation condition
pub fn primitive_violation_p(args: &[Value]) -> Result<Value> {
    if args.len() != 1 {
        return Err(Box::new(DiagnosticError::runtime_error(
            format!("violation?: expected 1 argument, got {}", args.len()),
            None,
        )));
    }

    match &args[0] {
        Value::Condition(condition_value) => {
            let system = condition_system();
            Ok(Value::boolean(
                condition_value.condition.has_type(system.standard_types.violation, &system.registry)
            ))
        }
        _ => Ok(Value::boolean(false)),
    }
}

/// assertion-violation? - tests if object is an assertion violation condition
pub fn primitive_assertion_violation_p(args: &[Value]) -> Result<Value> {
    if args.len() != 1 {
        return Err(Box::new(DiagnosticError::runtime_error(
            format!("assertion-violation?: expected 1 argument, got {}", args.len()),
            None,
        )));
    }

    match &args[0] {
        Value::Condition(condition_value) => {
            let system = condition_system();
            Ok(Value::boolean(
                condition_value.condition.has_type(system.standard_types.assertion, &system.registry)
            ))
        }
        _ => Ok(Value::boolean(false)),
    }
}

/// non-continuable-violation? - tests if object is a non-continuable violation condition
pub fn primitive_non_continuable_violation_p(args: &[Value]) -> Result<Value> {
    if args.len() != 1 {
        return Err(Box::new(DiagnosticError::runtime_error(
            format!("non-continuable-violation?: expected 1 argument, got {}", args.len()),
            None,
        )));
    }

    match &args[0] {
        Value::Condition(condition_value) => {
            let system = condition_system();
            Ok(Value::boolean(
                condition_value.condition.has_type(system.standard_types.non_continuable, &system.registry)
            ))
        }
        _ => Ok(Value::boolean(false)),
    }
}

/// implementation-restriction-violation? - tests if object is an implementation restriction violation condition
pub fn primitive_implementation_restriction_violation_p(args: &[Value]) -> Result<Value> {
    if args.len() != 1 {
        return Err(Box::new(DiagnosticError::runtime_error(
            format!("implementation-restriction-violation?: expected 1 argument, got {}", args.len()),
            None,
        )));
    }

    match &args[0] {
        Value::Condition(condition_value) => {
            let system = condition_system();
            Ok(Value::boolean(
                condition_value.condition.has_type(system.standard_types.implementation_restriction, &system.registry)
            ))
        }
        _ => Ok(Value::boolean(false)),
    }
}

// ============= STANDARD CONDITION ACCESSORS =============

/// condition-message - extracts the message from a message condition
pub fn primitive_condition_message(args: &[Value]) -> Result<Value> {
    if args.len() != 1 {
        return Err(Box::new(DiagnosticError::runtime_error(
            format!("condition-message: expected 1 argument, got {}", args.len()),
            None,
        )));
    }

    match &args[0] {
        Value::Condition(condition_value) => {
            let system = condition_system();
            let message_field = system.registry.get_interner().intern("message");
            
            if let Some(message) = condition_value.condition.condition_ref(message_field, &system.registry) {
                Ok(message.clone())
            } else {
                Err(Box::new(DiagnosticError::runtime_error(
                    "condition-message: condition does not have a message field".to_string(),
                    None,
                )))
            }
        }
        _ => Err(Box::new(DiagnosticError::runtime_error(
            "condition-message: expected condition object".to_string(),
            None,
        ))),
    }
}

// ============= HELPER FUNCTIONS =============

/// Parses field specifications from a list
fn parse_field_specs(value: &Value) -> Result<Vec<(String, String)>> {
    match value {
        Value::List(list) => {
            let mut field_specs = Vec::new();
            
            for item in list.iter() {
                match item {
                    Value::List(pair) => {
                        if pair.len() != 2 {
                            return Err(Box::new(DiagnosticError::runtime_error(
                                "Field specification must be (field accessor)".to_string(),
                                None,
                            )));
                        }
                        
                        let field_name = match &pair[0] {
                            Value::Literal(crate::ast::Literal::String(s)) => s.clone(),
                            _ => return Err(Box::new(DiagnosticError::runtime_error(
                                "Field name must be a string".to_string(),
                                None,
                            ))),
                        };
                        
                        let accessor_name = match &pair[1] {
                            Value::Literal(crate::ast::Literal::String(s)) => s.clone(),
                            _ => return Err(Box::new(DiagnosticError::runtime_error(
                                "Accessor name must be a string".to_string(),
                                None,
                            ))),
                        };
                        
                        field_specs.push((field_name, accessor_name));
                    }
                    _ => return Err(Box::new(DiagnosticError::runtime_error(
                        "Field specification must be a list".to_string(),
                        None,
                    ))),
                }
            }
            
            Ok(field_specs)
        }
        _ => Err(Box::new(DiagnosticError::runtime_error(
            "Field specifications must be a list".to_string(),
            None,
        ))),
    }
}

/// Parses field bindings from a list
fn parse_field_bindings(value: &Value) -> Result<Vec<(String, Value)>> {
    match value {
        Value::List(list) => {
            let mut field_bindings = Vec::new();
            
            for item in list.iter() {
                match item {
                    Value::Pair(pair) => {
                        let field_name = match &pair.car {
                            Value::Symbol(symbol_id) => {
                                // We need access to the interner to resolve the symbol
                                let system = condition_system();
                                system.registry.interner.resolve(*symbol_id).to_string()
                            }
                            _ => return Err(Box::new(DiagnosticError::runtime_error(
                                "Field name must be a symbol".to_string(),
                                None,
                            ))),
                        };
                        
                        field_bindings.push((field_name, pair.cdr.clone()));
                    }
                    _ => return Err(Box::new(DiagnosticError::runtime_error(
                        "Field binding must be a pair".to_string(),
                        None,
                    ))),
                }
            }
            
            Ok(field_bindings)
        }
        _ => Err(Box::new(DiagnosticError::runtime_error(
            "Field bindings must be a list".to_string(),
            None,
        ))),
    }
}

/// Binds all SRFI-35 procedures to an environment
pub fn bind_srfi35_procedures(env: &Arc<crate::eval::Environment>) -> Result<()> {
    use crate::eval::value::{PrimitiveProcedure, PrimitiveImpl};

    // Macro support procedures (internal)
    env.define(
        "%register-condition-type",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "%register-condition-type".to_string(),
            arity_min: 5,
            arity_max: Some(5),
            implementation: PrimitiveImpl::RustFn(primitive_register_condition_type),
            effects: vec![],
        })),
    )?;

    env.define(
        "%get-condition-type",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "%get-condition-type".to_string(),
            arity_min: 1,
            arity_max: Some(1),
            implementation: PrimitiveImpl::RustFn(primitive_get_condition_type),
            effects: vec![],
        })),
    )?;

    env.define(
        "%make-condition",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "%make-condition".to_string(),
            arity_min: 2,
            arity_max: Some(2),
            implementation: PrimitiveImpl::RustFn(primitive_make_condition),
            effects: vec![],
        })),
    )?;

    // Core condition procedures
    env.define(
        "condition",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "condition".to_string(),
            arity_min: 1,
            arity_max: None,
            implementation: PrimitiveImpl::RustFn(primitive_condition),
            effects: vec![],
        })),
    )?;

    env.define(
        "simple-conditions",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "simple-conditions".to_string(),
            arity_min: 1,
            arity_max: Some(1),
            implementation: PrimitiveImpl::RustFn(primitive_simple_conditions),
            effects: vec![],
        })),
    )?;

    env.define(
        "condition?",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "condition?".to_string(),
            arity_min: 1,
            arity_max: Some(1),
            implementation: PrimitiveImpl::RustFn(primitive_condition_p),
            effects: vec![],
        })),
    )?;

    env.define(
        "condition-has-type?",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "condition-has-type?".to_string(),
            arity_min: 2,
            arity_max: Some(2),
            implementation: PrimitiveImpl::RustFn(primitive_condition_has_type_p),
            effects: vec![],
        })),
    )?;

    env.define(
        "extract-condition",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "extract-condition".to_string(),
            arity_min: 2,
            arity_max: Some(2),
            implementation: PrimitiveImpl::RustFn(primitive_extract_condition),
            effects: vec![],
        })),
    )?;

    env.define(
        "condition-ref",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "condition-ref".to_string(),
            arity_min: 2,
            arity_max: Some(2),
            implementation: PrimitiveImpl::RustFn(primitive_condition_ref),
            effects: vec![],
        })),
    )?;

    // Standard condition constructors
    env.define(
        "make-condition",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "make-condition".to_string(),
            arity_min: 0,
            arity_max: Some(0),
            implementation: PrimitiveImpl::RustFn(primitive_make_condition_root),
            effects: vec![],
        })),
    )?;

    env.define(
        "make-message-condition",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "make-message-condition".to_string(),
            arity_min: 1,
            arity_max: Some(1),
            implementation: PrimitiveImpl::RustFn(primitive_make_message_condition),
            effects: vec![],
        })),
    )?;

    env.define(
        "make-serious-condition",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "make-serious-condition".to_string(),
            arity_min: 0,
            arity_max: Some(0),
            implementation: PrimitiveImpl::RustFn(primitive_make_serious_condition),
            effects: vec![],
        })),
    )?;

    env.define(
        "make-error",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "make-error".to_string(),
            arity_min: 0,
            arity_max: Some(0),
            implementation: PrimitiveImpl::RustFn(primitive_make_error),
            effects: vec![],
        })),
    )?;

    env.define(
        "make-violation",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "make-violation".to_string(),
            arity_min: 0,
            arity_max: Some(0),
            implementation: PrimitiveImpl::RustFn(primitive_make_violation),
            effects: vec![],
        })),
    )?;

    env.define(
        "make-assertion-violation",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "make-assertion-violation".to_string(),
            arity_min: 0,
            arity_max: Some(0),
            implementation: PrimitiveImpl::RustFn(primitive_make_assertion_violation),
            effects: vec![],
        })),
    )?;

    env.define(
        "make-non-continuable-violation",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "make-non-continuable-violation".to_string(),
            arity_min: 0,
            arity_max: Some(0),
            implementation: PrimitiveImpl::RustFn(primitive_make_non_continuable_violation),
            effects: vec![],
        })),
    )?;

    env.define(
        "make-implementation-restriction-violation",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "make-implementation-restriction-violation".to_string(),
            arity_min: 0,
            arity_max: Some(0),
            implementation: PrimitiveImpl::RustFn(primitive_make_implementation_restriction_violation),
            effects: vec![],
        })),
    )?;

    // Standard condition predicates
    env.define(
        "message-condition?",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "message-condition?".to_string(),
            arity_min: 1,
            arity_max: Some(1),
            implementation: PrimitiveImpl::RustFn(primitive_message_condition_p),
            effects: vec![],
        })),
    )?;

    env.define(
        "serious-condition?",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "serious-condition?".to_string(),
            arity_min: 1,
            arity_max: Some(1),
            implementation: PrimitiveImpl::RustFn(primitive_serious_condition_p),
            effects: vec![],
        })),
    )?;

    env.define(
        "error?",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "error?".to_string(),
            arity_min: 1,
            arity_max: Some(1),
            implementation: PrimitiveImpl::RustFn(primitive_error_p),
            effects: vec![],
        })),
    )?;

    env.define(
        "violation?",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "violation?".to_string(),
            arity_min: 1,
            arity_max: Some(1),
            implementation: PrimitiveImpl::RustFn(primitive_violation_p),
            effects: vec![],
        })),
    )?;

    env.define(
        "assertion-violation?",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "assertion-violation?".to_string(),
            arity_min: 1,
            arity_max: Some(1),
            implementation: PrimitiveImpl::RustFn(primitive_assertion_violation_p),
            effects: vec![],
        })),
    )?;

    env.define(
        "non-continuable-violation?",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "non-continuable-violation?".to_string(),
            arity_min: 1,
            arity_max: Some(1),
            implementation: PrimitiveImpl::RustFn(primitive_non_continuable_violation_p),
            effects: vec![],
        })),
    )?;

    env.define(
        "implementation-restriction-violation?",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "implementation-restriction-violation?".to_string(),
            arity_min: 1,
            arity_max: Some(1),
            implementation: PrimitiveImpl::RustFn(primitive_implementation_restriction_violation_p),
            effects: vec![],
        })),
    )?;

    // Standard condition accessors
    env.define(
        "condition-message",
        Value::Primitive(Arc::new(PrimitiveProcedure {
            name: "condition-message".to_string(),
            arity_min: 1,
            arity_max: Some(1),
            implementation: PrimitiveImpl::RustFn(primitive_condition_message),
            effects: vec![],
        })),
    )?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::utils::string_interner::StringInterner;

    #[test]
    fn test_register_condition_type() {
        let interner = Arc::new(StringInterner::new());
        initialize_condition_system(interner).unwrap();
        
        let args = vec![
            Value::string("&my-error".to_string()),
            Value::string("&error".to_string()),
            Value::string("make-my-error".to_string()),
            Value::string("my-error?".to_string()),
            Value::list_from_vec(vec![]), // No fields
        ];
        
        let result = primitive_register_condition_type(&args);
        assert!(result.is_ok());
        
        match result.unwrap() {
            Value::ConditionType(_) => {}, // Success
            _ => panic!("Expected condition type"),
        }
    }

    #[test]
    fn test_make_message_condition() {
        let interner = Arc::new(StringInterner::new());
        initialize_condition_system(interner).unwrap();
        
        let args = vec![Value::string("Test message".to_string())];
        let result = primitive_make_message_condition(&args);
        
        assert!(result.is_ok());
        match result.unwrap() {
            Value::Condition(_) => {}, // Success
            _ => panic!("Expected condition object"),
        }
    }

    #[test]
    fn test_condition_predicate() {
        let interner = Arc::new(StringInterner::new());
        initialize_condition_system(interner).unwrap();
        
        // Test with a condition object
        let condition = primitive_make_message_condition(&[Value::string("Test".to_string())]).unwrap();
        let result = primitive_condition_p(&[condition]);
        assert_eq!(result.unwrap(), Value::boolean(true));
        
        // Test with a non-condition object
        let result = primitive_condition_p(&[Value::integer(42)]);
        assert_eq!(result.unwrap(), Value::boolean(false));
    }
}