//! Dynamic library loading and hot-reload support.
//!
//! This module provides comprehensive dynamic loading capabilities including:
//! - Runtime library loading and unloading
//! - Hot-reload support with dependency tracking
//! - File system monitoring for automatic reloading
//! - Safe hot-swapping of library implementations

use super::{Module, ModuleError, ModuleId, runtime_integration};
use crate::ast::Expr;
use crate::diagnostics::{Error, Result};
use crate::lexer::Lexer;
use crate::parser::Parser;
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::{Arc, RwLock, mpsc};
use std::thread;
use std::time::{Duration, SystemTime};

/// Dynamic library loader with hot-reload capabilities.
#[derive(Debug)]
pub struct DynamicLibraryLoader {
    /// Active library instances
    active_libraries: Arc<RwLock<HashMap<ModuleId, DynamicLibraryInstance>>>,
    /// File system monitoring configuration
    monitor_config: FileMonitorConfig,
    /// Hot-reload event sender
    reload_sender: Option<mpsc::Sender<ReloadEvent>>,
    /// Reload generation counter
    reload_generation: Arc<std::sync::atomic::AtomicU64>,
    /// Dependency tracking for reload impact analysis
    dependency_tracker: DependencyTracker,
}

/// A dynamically loaded library instance.
#[derive(Debug, Clone)]
pub struct DynamicLibraryInstance {
    /// The instantiated library
    pub library: Arc<runtime_integration::LibraryInstance>,
    /// Source file path for hot-reload monitoring
    pub source_path: Option<PathBuf>,
    /// Last modification time of source file
    pub last_modified: SystemTime,
    /// Load generation (for hot-reload tracking)
    pub load_generation: u64,
    /// Dependent libraries that need reloading if this changes
    pub dependents: HashSet<ModuleId>,
    /// Whether this library supports hot-reload
    pub hot_reload_enabled: bool,
}

/// Configuration for file system monitoring.
#[derive(Debug, Clone)]
pub struct FileMonitorConfig {
    /// Whether to enable file system monitoring
    pub enable_monitoring: bool,
    /// Polling interval for file changes
    pub poll_interval: Duration,
    /// File extensions to monitor
    pub monitored_extensions: Vec<String>,
    /// Directories to monitor
    pub monitored_directories: Vec<PathBuf>,
    /// Whether to enable recursive monitoring
    pub recursive_monitoring: bool,
}

impl Default for FileMonitorConfig {
    fn default() -> Self {
        Self {
            enable_monitoring: true,
            poll_interval: Duration::from_millis(500),
            monitored_extensions: vec![".scm".to_string(), ".lisp".to_string()],
            monitored_directories: Vec::new(),
            recursive_monitoring: true,
        }
    }
}

/// Events generated by the hot-reload system.
#[derive(Debug, Clone)]
pub enum ReloadEvent {
    /// A source file has been modified
    FileModified {
        /// File path that was modified
        path: PathBuf,
        /// Module ID corresponding to the modified file
        module_id: ModuleId,
    },
    /// A library has been successfully reloaded
    LibraryReloaded {
        /// Module ID that was reloaded
        module_id: ModuleId,
        /// New generation number after reload
        generation: u64,
    },
    /// A reload failed with an error
    ReloadFailed {
        /// Module ID that failed to reload
        module_id: ModuleId,
        /// Error message describing the failure
        error: String,
    },
    /// Dependencies have been invalidated
    DependenciesInvalidated {
        /// List of modules affected by the invalidation
        affected_modules: Vec<ModuleId>,
    },
}

/// Tracks dependencies for impact analysis during hot-reload.
#[derive(Debug, Default)]
pub struct DependencyTracker {
    /// Forward dependency map (module -> its dependencies)
    forward_deps: HashMap<ModuleId, HashSet<ModuleId>>,
    /// Reverse dependency map (module -> modules that depend on it)
    reverse_deps: HashMap<ModuleId, HashSet<ModuleId>>,
}

impl DynamicLibraryLoader {
    /// Creates a new dynamic library loader.
    pub fn new() -> Self {
        Self::with_config(FileMonitorConfig::default())
    }

    /// Creates a loader with custom monitoring configuration.
    pub fn with_config(config: FileMonitorConfig) -> Self {
        Self {
            active_libraries: Arc::new(RwLock::new(HashMap::new())),
            monitor_config: config,
            reload_sender: None,
            reload_generation: Arc::new(std::sync::atomic::AtomicU64::new(1)),
            dependency_tracker: DependencyTracker::default(),
        }
    }

    /// Loads a library dynamically with hot-reload support.
    pub fn load_library_dynamic(
        &mut self,
        module: Module,
        instantiator: &mut runtime_integration::LibraryInstantiator,
        enable_hot_reload: bool,
    ) -> Result<Arc<DynamicLibraryInstance>> {
        let module_id = module.id.clone();

        // Check if already loaded
        {
            let active_libs = self.active_libraries.try_read().unwrap();
            if let Some(existing) = active_libs.get(&module_id) {
                return Ok(Arc::new(existing.clone()));
            }
        }

        // Instantiate the library
        let library_instance = instantiator.instantiate_library(module.clone())?;

        // Determine source path for monitoring
        let source_path = self.get_source_path_for_module(&module);
        let last_modified = if let Some(path) = &source_path {
            fs::metadata(path)
                .and_then(|m| m.modified())
                .unwrap_or_else(|_| SystemTime::now())
        } else {
            SystemTime::now()
        };

        // Create dynamic instance
        let dynamic_instance = DynamicLibraryInstance {
            library: library_instance,
            source_path: source_path.clone(),
            last_modified,
            load_generation: self
                .reload_generation
                .load(std::sync::atomic::Ordering::Relaxed),
            dependents: HashSet::new(),
            hot_reload_enabled: enable_hot_reload,
        };

        // Track dependencies
        self.track_dependencies(&module);

        // Add to active libraries
        {
            let mut active_libs = self.active_libraries.write().unwrap();
            active_libs.insert(module_id.clone(), dynamic_instance.clone());
        }

        // Start monitoring if enabled
        if enable_hot_reload && self.monitor_config.enable_monitoring {
            if let Some(path) = source_path {
                self.start_monitoring_file(&path, &module_id)?;
            }
        }

        Ok(Arc::new(dynamic_instance))
    }

    /// Reloads a library and its dependents.
    pub fn reload_library(
        &mut self,
        module_id: &ModuleId,
        instantiator: &mut runtime_integration::LibraryInstantiator,
    ) -> Result<()> {
        // Get current instance
        let current_instance = {
            let active_libs = self.active_libraries.try_read().unwrap();
            active_libs.get(module_id).cloned()
        };

        let current_instance = current_instance.ok_or_else(|| {
            Error::from(ModuleError::DynamicLoadingError(format!(
                "Library not loaded: {}",
                super::format_module_id(module_id)
            )))
        })?;

        // Check if hot-reload is enabled
        if !current_instance.hot_reload_enabled {
            return Err(Box::new(Error::from(ModuleError::HotReloadError(format!(
                "Hot-reload not enabled for library: {}",
                super::format_module_id(module_id)
            )))));
        }

        // Load the module from source
        let source_path = current_instance.source_path.ok_or_else(|| {
            Error::from(ModuleError::HotReloadError(
                "No source path available for hot-reload".to_string(),
            ))
        })?;

        let reloaded_module = self.load_module_from_file(&source_path, module_id)?;

        // Clear instantiation cache for this library
        instantiator.clear_cache();

        // Reinstantiate the library
        let new_instance = instantiator.instantiate_library(reloaded_module)?;

        // Update the dynamic instance
        let new_generation = self
            .reload_generation
            .fetch_add(1, std::sync::atomic::Ordering::Relaxed)
            + 1;

        let updated_instance = DynamicLibraryInstance {
            library: new_instance,
            source_path: Some(source_path.clone()),
            last_modified: SystemTime::now(),
            load_generation: new_generation,
            dependents: current_instance.dependents.clone(),
            hot_reload_enabled: true,
        };

        // Update active libraries
        {
            let mut active_libs = self.active_libraries.write().unwrap();
            active_libs.insert(module_id.clone(), updated_instance);
        }

        // Send reload event
        if let Some(sender) = &self.reload_sender {
            let _ = sender.send(ReloadEvent::LibraryReloaded {
                module_id: module_id.clone(),
                generation: new_generation,
            });
        }

        // Reload dependents
        self.reload_dependents(module_id, instantiator)?;

        Ok(())
    }

    /// Unloads a library and removes it from monitoring.
    pub fn unload_library(&mut self, module_id: &ModuleId) -> Result<()> {
        // Remove from active libraries
        {
            let mut active_libs = self.active_libraries.write().unwrap();
            active_libs.remove(module_id);
        }

        // Remove from dependency tracking
        self.dependency_tracker.remove_module(module_id);

        // Stop monitoring (if any file watchers were active)
        // In a full implementation, we would track and stop file watchers here

        Ok(())
    }

    /// Enables hot-reload event monitoring.
    pub fn enable_event_monitoring(&mut self) -> mpsc::Receiver<ReloadEvent> {
        let (sender, receiver) = mpsc::channel();
        self.reload_sender = Some(sender);
        receiver
    }

    /// Gets information about all active libraries.
    pub fn get_active_libraries(&self) -> HashMap<ModuleId, DynamicLibraryInstance> {
        let active_libs = self.active_libraries.try_read().unwrap();
        active_libs.clone()
    }

    /// Checks for file modifications and triggers reloads.
    pub fn check_for_modifications(
        &mut self,
        instantiator: &mut runtime_integration::LibraryInstantiator,
    ) -> Result<Vec<ModuleId>> {
        let mut reloaded_modules = Vec::new();
        let modifications = self.detect_file_modifications()?;

        for (module_id, _modified_path) in modifications {
            if let Ok(()) = self.reload_library(&module_id, instantiator) {
                reloaded_modules.push(module_id);
            }
        }

        Ok(reloaded_modules)
    }

    /// Detects file modifications for all monitored libraries.
    fn detect_file_modifications(&self) -> Result<Vec<(ModuleId, PathBuf)>> {
        let mut modifications = Vec::new();
        let active_libs = self.active_libraries.try_read().unwrap();

        for (module_id, instance) in active_libs.iter() {
            if let Some(source_path) = &instance.source_path {
                if let Ok(metadata) = fs::metadata(source_path) {
                    if let Ok(modified_time) = metadata.modified() {
                        if modified_time > instance.last_modified {
                            modifications.push((module_id.clone(), source_path.clone()));
                        }
                    }
                }
            }
        }

        Ok(modifications)
    }

    /// Loads a module from a file path.
    fn load_module_from_file(&self, path: &Path, module_id: &ModuleId) -> Result<Module> {
        let source_code = fs::read_to_string(path).map_err(|e| {
            Error::io_error(format!(
                "Failed to read library file {}: {}",
                path.display(),
                e
            ))
        })?;

        // Parse the source code
        let binding = path.to_string_lossy();
        let mut lexer = Lexer::new(&source_code, Some(&binding));
        let tokens = lexer.tokenize()?;
        let mut parser = Parser::new(tokens);
        let program = parser.try_parse_program()?;

        // Look for define-library forms
        for expr in &program.expressions {
            if let Expr::DefineLibrary {
                name,
                imports,
                exports,
                body,
            } = &expr.inner
            {
                // Create module from define-library form
                let parsed_module = Module {
                    id: module_id.clone(),
                    exports: HashMap::new(), // Would be populated from exports
                    dependencies: Vec::new(), // Would be populated from imports
                    source: Some(super::ModuleSource::File(path.to_path_buf())),
                    metadata: super::ModuleMetadata {
                        description: Some(format!("Library: {}", name.join(" "))),
                        ..Default::default()
                    },
                };
                return Ok(parsed_module);
            }
        }

        // Fallback: create a basic module
        Ok(Module {
            id: module_id.clone(),
            exports: HashMap::new(),
            dependencies: Vec::new(),
            source: Some(super::ModuleSource::File(path.to_path_buf())),
            metadata: super::ModuleMetadata::default(),
        })
    }

    /// Gets the source path for a module.
    fn get_source_path_for_module(&self, module: &Module) -> Option<PathBuf> {
        match &module.source {
            Some(super::ModuleSource::File(path)) => Some(path.clone()),
            _ => None,
        }
    }

    /// Tracks dependencies for a module.
    fn track_dependencies(&mut self, module: &Module) {
        let module_id = &module.id;

        // Track forward dependencies
        self.dependency_tracker.forward_deps.insert(
            module_id.clone(),
            module.dependencies.iter().cloned().collect(),
        );

        // Track reverse dependencies
        for dep_id in &module.dependencies {
            self.dependency_tracker
                .reverse_deps
                .entry(dep_id.clone())
                .or_default()
                .insert(module_id.clone());
        }
    }

    /// Starts monitoring a file for changes.
    fn start_monitoring_file(&self, _path: &Path, _module_id: &ModuleId) -> Result<()> {
        // In a full implementation, this would set up file system watchers
        // For now, we rely on periodic polling via check_for_modifications
        Ok(())
    }

    /// Reloads all libraries that depend on the given module.
    fn reload_dependents(
        &mut self,
        module_id: &ModuleId,
        instantiator: &mut runtime_integration::LibraryInstantiator,
    ) -> Result<()> {
        let dependents = self
            .dependency_tracker
            .reverse_deps
            .get(module_id)
            .cloned()
            .unwrap_or_default();

        let mut failed_reloads = Vec::new();

        for dependent_id in dependents {
            if let Err(e) = self.reload_library(&dependent_id, instantiator) {
                failed_reloads.push((dependent_id.clone(), e.to_string()));
            }
        }

        // Send dependency invalidation event
        if let Some(sender) = &self.reload_sender {
            let affected_modules: Vec<ModuleId> =
                failed_reloads.iter().map(|(id, _)| id.clone()).collect();

            if !affected_modules.is_empty() {
                let _ = sender.send(ReloadEvent::DependenciesInvalidated { affected_modules });
            }
        }

        if !failed_reloads.is_empty() {
            return Err(Box::new(Error::from(ModuleError::HotReloadError(format!(
                "Failed to reload {} dependent libraries",
                failed_reloads.len()
            )))));
        }

        Ok(())
    }

    /// Gets statistics about the dynamic loading system.
    pub fn get_statistics(&self) -> DynamicLoadingStatistics {
        let active_libs = self.active_libraries.try_read().unwrap();
        let hot_reload_enabled = active_libs
            .values()
            .filter(|lib| lib.hot_reload_enabled)
            .count();

        DynamicLoadingStatistics {
            total_active_libraries: active_libs.len(),
            hot_reload_enabled_libraries: hot_reload_enabled,
            current_reload_generation: self
                .reload_generation
                .load(std::sync::atomic::Ordering::Relaxed),
            monitored_files: active_libs
                .values()
                .filter_map(|lib| lib.source_path.as_ref())
                .count(),
        }
    }
}

impl DependencyTracker {
    /// Removes a module from dependency tracking.
    fn remove_module(&mut self, module_id: &ModuleId) {
        // Remove from forward dependencies
        if let Some(deps) = self.forward_deps.remove(module_id) {
            // Update reverse dependencies
            for dep_id in deps {
                if let Some(reverse_deps) = self.reverse_deps.get_mut(&dep_id) {
                    reverse_deps.remove(module_id);
                    if reverse_deps.is_empty() {
                        self.reverse_deps.remove(&dep_id);
                    }
                }
            }
        }

        // Remove from reverse dependencies
        self.reverse_deps.remove(module_id);
    }
}

/// Statistics about the dynamic loading system.
#[derive(Debug, Clone)]
pub struct DynamicLoadingStatistics {
    /// Total number of active libraries
    pub total_active_libraries: usize,
    /// Number of libraries with hot-reload enabled
    pub hot_reload_enabled_libraries: usize,
    /// Current reload generation
    pub current_reload_generation: u64,
    /// Number of files being monitored
    pub monitored_files: usize,
}

impl Default for DynamicLibraryLoader {
    fn default() -> Self {
        Self::new()
    }
}

/// Hot-reload manager for coordinating automatic reloading.
#[derive(Debug)]
pub struct HotReloadManager {
    /// The dynamic loader
    loader: DynamicLibraryLoader,
    /// Event receiver for reload events
    event_receiver: Option<mpsc::Receiver<ReloadEvent>>,
    /// Whether the manager is running
    running: Arc<std::sync::atomic::AtomicBool>,
    /// Manager thread handle
    _manager_thread: Option<thread::JoinHandle<()>>,
}

impl HotReloadManager {
    /// Creates a new hot-reload manager.
    pub fn new(loader: DynamicLibraryLoader) -> Self {
        Self {
            loader,
            event_receiver: None,
            running: Arc::new(std::sync::atomic::AtomicBool::new(false)),
            _manager_thread: None,
        }
    }

    /// Starts the hot-reload manager.
    pub fn start(&mut self) -> Result<()> {
        if self.running.load(std::sync::atomic::Ordering::Relaxed) {
            return Ok(()); // Already running
        }

        let receiver = self.loader.enable_event_monitoring();
        self.event_receiver = Some(receiver);
        self.running
            .store(true, std::sync::atomic::Ordering::Relaxed);

        // In a full implementation, we would start a background thread
        // to handle file monitoring and automatic reloading

        Ok(())
    }

    /// Stops the hot-reload manager.
    pub fn stop(&mut self) {
        self.running
            .store(false, std::sync::atomic::Ordering::Relaxed);
        self.event_receiver = None;
    }

    /// Checks for and processes any pending reload events.
    pub fn process_events(&mut self) -> Vec<ReloadEvent> {
        let mut events = Vec::new();

        if let Some(receiver) = &self.event_receiver {
            while let Ok(event) = receiver.try_recv() {
                events.push(event);
            }
        }

        events
    }

    /// Gets the underlying loader.
    pub fn loader(&mut self) -> &mut DynamicLibraryLoader {
        &mut self.loader
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::module_system::{ModuleMetadata, ModuleNamespace, ModuleSource};
    use crate::runtime::GlobalEnvironmentManager;
    use tempfile::TempDir;

    fn create_test_module(name: &str) -> Module {
        Module {
            id: ModuleId {
                components: vec![name.to_string()],
                namespace: ModuleNamespace::User,
            },
            exports: HashMap::new(),
            dependencies: Vec::new(),
            source: Some(ModuleSource::Builtin),
            metadata: ModuleMetadata::default(),
        }
    }

    #[test]
    fn test_dynamic_loader_creation() {
        let loader = DynamicLibraryLoader::new();
        let stats = loader.get_statistics();
        assert_eq!(stats.total_active_libraries, 0);
    }

    #[test]
    fn test_library_loading() {
        let mut loader = DynamicLibraryLoader::new();
        let global_env = Arc::new(GlobalEnvironmentManager::new());
        let mut instantiator = runtime_integration::LibraryInstantiator::new(global_env);

        let module = create_test_module("test");
        let result = loader.load_library_dynamic(module, &mut instantiator, false);

        assert!(result.is_ok());
        let stats = loader.get_statistics();
        assert_eq!(stats.total_active_libraries, 1);
    }

    #[test]
    fn test_hot_reload_manager() {
        let loader = DynamicLibraryLoader::new();
        let mut manager = HotReloadManager::new(loader);

        let result = manager.start();
        assert!(result.is_ok());

        manager.stop();
    }

    #[test]
    fn test_dependency_tracking() {
        let mut tracker = DependencyTracker::default();
        let module_a = ModuleId {
            components: vec!["a".to_string()],
            namespace: ModuleNamespace::User,
        };
        let module_b = ModuleId {
            components: vec!["b".to_string()],
            namespace: ModuleNamespace::User,
        };

        // Add dependency: A depends on B
        tracker.forward_deps.insert(module_a.clone(), {
            let mut deps = HashSet::new();
            deps.insert(module_b.clone());
            deps
        });
        tracker.reverse_deps.insert(module_b.clone(), {
            let mut deps = HashSet::new();
            deps.insert(module_a.clone());
            deps
        });

        // Remove module A
        tracker.remove_module(&module_a);

        assert!(!tracker.forward_deps.contains_key(&module_a));
        assert!(!tracker.reverse_deps.contains_key(&module_b));
    }

    #[test]
    fn test_file_monitoring_config() {
        let config = FileMonitorConfig {
            enable_monitoring: true,
            poll_interval: Duration::from_millis(100),
            monitored_extensions: vec![".scm".to_string()],
            monitored_directories: vec![],
            recursive_monitoring: false,
        };

        let loader = DynamicLibraryLoader::with_config(config);
        assert!(loader.monitor_config.enable_monitoring);
        assert_eq!(
            loader.monitor_config.poll_interval,
            Duration::from_millis(100)
        );
    }
}
